- title: Education
  type: time_table
  contents:
    - title: PhD on Applied Cryptography on Blockchain
      institution: Universitat Oberta de Catalunya, Barcelona, Spain
      year: 2021 - Present
    - title: MSc in Fundamental Principles of Data Science 
      institution: Universitat de Barcelona, Barcelona, Spain
      year: 2020 - 2021
      description:
        - Description 1.
        - Description 2.
    - title: Double BSc in Mathematics and Computer Science
      institution: Universitat de Barcelona, Barcelona, Spain
      year: 2013 - 2020
      description:
        - Description 1.
        - Description 2.
        - title: Description 3.
          contents:
            - Sub-description 1.
            - Sub-description 2.

- title: Experience
  type: time_table
  contents:
    - title: Professor of Theoretical Physics
      institution: Institute for Advanced Study, Princeton University
      year: 1933 - 1955
      description:
        - Description 1.
        - Description 2.
        - title: Description 3.
          contents:
            - Sub-description 1.
            - Sub-description 2.
    - title: Visiting Professor
      institution: California Institute of Technology, Pasadena, California, US
      year: 1933
      description:
        - Description 1.
        - Description 2.

    - title: Director
      institution: Kaiser Wilhelm Institute for Physics, Berlin, Germany.
      year: 1917-1933

    - title: Professor of Theoretical Physics
      institution: Karl-Ferdinand University, Prague, Czechoslovakia
      year: 1911 - 1917
      description:

    - title: Associate Professor of Theoretical Physics
      institution: University of Zurich, Zurich, Switzerland
      year: 1909 - 1911

- title: Grants and Awards
  type: time_table
  contents:
    - year: 1921
      items:
        - Nobel Prize in Physics
        - Matteucci Medal
    - year: 2029
      items:
        - Max Planck Medal

- title: Scientific Committee Participation
  type: time_table
  contents:
    - item: External reviewer
      - title: [Poster Jury for IEEE S&P 2025](https://www.ieee-security.org/TC/SP2025/cfposters.html)
        year: 2025
      - title: Reviewer for SECRYPT 2025.
        year: 2025

- title: Supervision
  type: list
  contents:
    - <u>Hobbies:</u> Hobby 1, Hobby 2, etc.
