# Regression guard.
# - Bug: _data/contributions.yml is auto-regenerated by scripts/refresh_contributions.py.
#   The HEADER constant in the Python script documents that the file is
#   auto-generated and MUST NOT be edited by hand. If someone refactors
#   the Python script and drops the header, future edits risk being
#   silently reverted by the next cron run.
# - Why this test exists: ensure the AUTO-GENERATED warning stays visible
#   inside _data/contributions.yml as long as the refresh script owns it.

RSpec.describe "_data/contributions.yml header preservation" do
  let(:data_path) { repo_path("_data/contributions.yml") }
  let(:script_path) { repo_path("scripts/refresh_contributions.py") }

  it "the AUTO-GENERATED warning is present in the first 20 lines" do
    first_lines = File.readlines(data_path).first(20).join
    expect(first_lines).to include("AUTO-GENERATED"),
      "_data/contributions.yml lost its AUTO-GENERATED header comment"
    expect(first_lines).to include("DO NOT EDIT BY HAND")
    expect(first_lines).to include("refresh_contributions.py")
  end

  it "the Python script still defines a HEADER constant with the warning" do
    script = File.read(script_path)
    expect(script).to match(/^HEADER\s*=/),
      "HEADER constant missing from refresh_contributions.py"
    expect(script).to include("AUTO-GENERATED")
  end
end
